### ISSUE TITLE
Helo

### ISSUE THREAD

**Issue by wintrmvte** [D3Ext/maldev#21]
Great job stealing my code/idea kurwo zajebana <3

**Comment by D3Ext** [comment]
?

**Comment by D3Ext** [comment]
I didn't know your project before I started coding mine. Indeed my repo is very different from yours and I haven't copied your code

**Comment by D3Ext** [comment]
From what I see, many of your functions execute commands using CMD or Bash but my functions perform all operations using Golang code, not commands. Also my project has many more encoding and encryption algorithms supported, more stuff related to shellcode execution based on my other repo and much more. Some functions may be similar because they are basic tasks a malware dev library should be able to do

**Comment by wintrmvte** [comment]
Cool
